import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import {Poppins} from "next/font/google";
import { CategoryProvider } from "@/context/CategoryContext";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400','500','600','700'],
  variable: "--font-poppins",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <div className="mx-auto max-w-screen-lg">
          <CategoryProvider>
            <div className="flex min-h-screen flex-col">
              {children}
            </div>
          </CategoryProvider>
        </div>
      </body>
    </html>
  );
}
